config/routes.rb
Cleanmycity::Application.routes.draw do
  devise_for :users

  resources :homes do
    get :dashboard, :on => :collection
  end

  resources :activities do
    post :comment, :on => :member
    post :email, :on => :member
    get :shame, :on => :member
  end
  resources :friendships
   root :to => 'homes#index'
  scope "/api" do
    post "/:action", :controller => "api"
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :category
  has_one :location
  has_many :shames
  has_many :comments
  serialize :media, Array
  accepts_nested_attributes_for :location


  attr_accessible :activity_for, :contact_person, :description, :is_anonymous, :media, :user_id, :category_id, :image, :location, :subject#, :location_attributes
  validates_presence_of :subject, :category_id, :description, :media#, :contact_person

  #def image_data=(data)
  #  # decode data and create stream on them
  # # io = ::CarrierStringIO.new(Base64.decode64(data))
  #
  #  # this will do the thing (photo is mounted carrierwave uploader)
  #  self.image = io
  #end

  def shame_count
    shames.count
  end
  def comment_count
    comments.count
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities
    @medias = Media.all.collect{|m| [m.name,m.id]}
    @categories = Category.all.collect{|m| [m.name,m.id]}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = current_user.activities.find(params[:id])
    @shames =  @activity.shames
    @comments = @activity.comments
    @is_shamed =  @activity.shame_ids.include?(current_user.id)
  respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = current_user.activities.new
    @location = @activity.build_location
    @medias = Media.all.collect{|m| [m.name,m.id]}
    @categories = Category.all.collect{|m| [m.name,m.id]}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = current_user.activities.find(params[:id])
    @medias = Media.all.collect{|m| [m.name,m.id]}
    @categories = Category.all.collect{|m| [m.name,m.id]}
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])
    @activity.user_id = current_user.id
    @location = @activity.build_location
    @medias = Media.all.collect{|m| [m.name,m.id]}
    @categories = Category.all.collect{|m| [m.name,m.id]}
    respond_to do |format|
      if @activity.save
        @location = Location.create(params[:location]) if params[:location].present?
        @location.update_attribute("activity_id",@activity.id) if params[:location].present?
        format.html { redirect_to activities_path, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  def comment
    @activity = Activity.find(params[:id])
    @comment  = @activity.comments.create(:user_id => current_user.id, :description => params[:description])
   if @comment.save
    redirect_to activity_path(@activity), :notice => "Thank You for posting the Comment"
   else
     redirect_to activity_path(@activity), :notice => "Sorry ! Empty comment is not Allowed"
   end
  end

  def shame
    @activity = Activity.find(params[:id])
    @comment  = @activity.shames.create(:user_id => current_user.id)
    if @comment.save
      redirect_to activity_path(@activity), :notice => "Thank You for Participate. it really help a lot to this activity"
    else
      redirect_to activity_path(@activity), :notice => "Sorry ! Empty comment is not Allowed"
    end
  end

  def email

  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <label>Activity Title</label>
      <%= f.text_field :subject   %>
    </div>
  <div class="field">
    <label>Select Category to which your Activity belongs</label>
    <%= f.select :category_id,  @categories,{:prompt => "Select Category"}   %>
  </div>
  <div class="field">
    <label> Choose Media</label>
    <%= f.select :media,  @medias,{},{ :multiple => true}  %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br />
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :is_anonymous %>
    <%= f.file_field :image %>
  </div>

    <div class="field">
      <label>Upload image which can support your activity</label>
      <%= f.check_box :is_anonymous %>
    </div>
    <% @activity.build_location if @activity.location.nil? %>
    <%= fields_for  @location  do |l|%>
        <div class="field">
          <label>Street Address</label>
          <%= l.text_field :street_address  %>
        </div>
        <div class="field">
          <label>City</label>
          <%= l.text_field :city %>
        </div>
        <div class="field">
          <label>State</label>
          <%= l.text_field :state %>
        </div>
        <div class="field">
       <label>Country</label>
          <%= l.text_field :country %>
        </div>
        <label>Postal Code</label>
        <%= l.text_field :postal_code %>
        </div>

    <% end %>
  <div class="actions">
    <%= f.submit "Create Activity", :class => "btn-primary" %>
    <%= link_to "cancel", :class => "btn-secondary"%>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="container">
<h1>Editing activity</h1>

<%= render 'form' %>
</div>

app/views/activities/index.html.erb
<div class="container activitiesWrap">
<h1>My Created  activities</h1>
<div class="btnContent">
  <%= link_to "Raise My Voice",new_activity_path, :class => "blueBtn btn"%>
</div>
<ul class="activitiesList">

  <% @activities.each do |activity| %>
  <li>
    <div class="imgBox"><%= image_tag(activity.image_url(:large), :size => "290x290")%></div>
    <div class="name"><%= activity.subject%></div>
    <div class="category"><%= activity.category.name%></div>
    <div class="created"> <%= activity.user.name %></div>
    <div class="description"> <%= activity.description%></div>
    <div class="scialLink">
      <a href="<%= activity_path(activity)%>" class="showIcon"></a>
      <a href="<%= edit_activity_path(activity)%>" class="editIcon"></a>
    <%= link_to "",activity_path(activity), :method => :delete,:class =>  "destroyIcon"%>
      <a onClick="window.open('http://www.facebook.com/sharer.php?s=100&amp;p[title]=<%= activity.subject %> - Clean My City&amp;p[summary]=<%=u activity.description %>&amp;p[url]=<%= activity_url(activity)%>&amp;&amp;p[images][0]=<%= "http://#{request.env["HTTP_HOST"]}#{activity.image_url}" %>','sharer','toolbar=0,status=0,width=548,height=325'); return false;" href="http://www.facebook.com/sharer.php?s=100&amp;p[title]=<%= activity.subject %> - Check-in For Good&amp;p[summary]=<%= activity.description %>&amp;p[url]=<%= activity_url(activity)%>&amp;&amp;" class="fbImgBig">Facebook</a>
      <a onClick="window.open('http://twitter.com/intent/tweet?text=Support this Activity: '+"<%= activity.name %>" +'&url=<%= activity_url(activity)%>&hashtags=CMC');  return false;" href="http://twitter.com/intent/tweet?text=Support this Activity: '<%= activity.name %> -'&url=<%= activity_url(activity)%>&hashtags=CMC" class="twitICon">Twitter</a>

    </div>
    <%= button_to "share with friends vie email",email_activity_path(activity), :class=>"blueBtn" %>
  </li>
      <% end %>

</ul>

</div>

app/views/activities/new.html.erb
<div class="container">
<h1>New activity</h1>

<%= render 'form' %>
</div>

app/views/activities/show.html.erb
<div class="container activityShowWrap">
  <div class="imgBox"><%= image_tag(@activity.image_url(:thumb), :size => "400x400")%></div>

  <div class="categoryAndCreated">
    <span class="category"><%= @activity.category.name%></span>
    <span class="created"><%= @activity.user.name%></span>
  </div>
  <p></p>
  <div class="shameAndCommentWrap">
    <span class="shameText">shame(<%= @activity.shames.count%>)</span>
    <span class="commentText">Comment(<%= @activity.comments.count %>)</span>
  </div>
  <div class="commentBox">
    <%= form_tag comment_activity_path(@activity) do | f|%>
        <label><strong>Add comment to this activity</strong></label>
        <%= text_area_tag :description,nil, :class =>"textarea" %>
        <%= submit_tag "comment", :class=>"blueBtn"%>
    <% end %>
  </div>
  <ul class="commentList">
    <% @activity.comments.each do |comment|%>
      <li>
        <div class="userImg"><%=image_tag("http://www.gravatar.com/avatar.php?gravatar_id=#{comment.user.gravatar_digest}", :size => "50x50")%></div>
        <div class="userDetail">
          <h4><%= comment.user.name%></h4>
          <p><%= comment.description%></p>
        </div>
      </li>
        <% end %>
  </ul>
  <div class="socialBox">
    <a onClick="window.open('http://www.facebook.com/sharer.php?s=100&amp;p[title]=<%= @activity.subject %> - Clean My City&amp;p[summary]=<%=u @activity.description %>&amp;p[url]=<%= activity_url(@activity)%>&amp;&amp;p[images][0]=<%= "http://#{request.env["HTTP_HOST"]}#{@activity.image_url}" %>','sharer','toolbar=0,status=0,width=548,height=325'); return false;" href="http://www.facebook.com/sharer.php?s=100&amp;p[title]=<%= @activity.subject %> - Check-in For Good&amp;p[summary]=<%= @activity.description %>&amp;p[url]=<%= activity_url(@activity)%>&amp;&amp;" class="fbImgBig">Facebook</a>
    <a onClick="window.open('http://twitter.com/intent/tweet?text=Support this Activity: '<%= @activity.name %> -'&url=<%= activity_url(@activity)%>&hashtags=CMC');  return false;" href="http://twitter.com/intent/tweet?text=Support this Activity: '<%= @activity.name %> -'&url=<%= activity_url(@activity)%>&hashtags=CMC" class="twitICon">Twitter</a>
    <%= link_to "Shame",shame_activity_path(@activity), :class => "shamIcon" unless @is_shamed%>
  </div>
  <%= link_to "share with friends vie email",email_activity_path(@activity) %>

 </div>